import type { NoteEvent } from "./notes";
import type { Direction } from "./input";
import type { BPMMap, StopMap } from "./timing";

// Kevin MacLeod – "In the Hall of the Mountain King" (CC BY 4.0)
export const SONG_FILE = "/audio/song.mp3";

// Seconds into the audio where beat 0 occurs (first aubio-detected downbeat).
export const OFFSET = 3.174271;

// Generated by tools/analyze.py --bpm 108, then adjusted by -OFFSET*(108/60) = -5.714 beats
// so that beat 0 = first musical downbeat, 1 beat = 1 musical beat.
export const BPMS: BPMMap = [
    [0,     108.0],  //   3.2s  opening
    [115.6, 126.6],  //  67.4s  accelerating section
    [212.5,  86.3],  // 113.3s  finale
];

// Pauses detected by aubio (gaps > 1.4× local average interval), offset-adjusted.
export const STOPS: StopMap = [
    [170.1, 0.197],
    [192.2, 0.262],
    [214.7, 0.338],
    [225.2, 0.575],
    [232.6, 0.303],
];

type Button = "A" | "B";

const A = "A";
const B = "B";
const UP           = "UP";
const DOWN         = "DOWN";
const LEFT         = "LEFT";
const RIGHT        = "RIGHT";
const UP_RIGHT     = "UP_RIGHT";
const UP_LEFT      = "UP_LEFT";
const DOWN_RIGHT   = "DOWN_RIGHT";
const DOWN_LEFT    = "DOWN_LEFT";

const t = (beat: number, dir: Direction, btn: Button): NoteEvent =>
    ({ beat, direction: dir, button: btn, type: "tap" });

const h = (beat: number, dir: Direction, btn: Button, dur: number): NoteEvent =>
    ({ beat, direction: dir, button: btn, type: "hold", duration: dur });

// Last aubio beat ≈ beat 267.5; add a short outro buffer.
export const SONG_LENGTH_BEATS = 276;

// Beats are 1:1 with musical beats (1 beat = 1 aubio-detected beat).
// Every 2 beats = every other musical beat (the natural "strong beat" grid).
export const CHART: NoteEvent[] = [
    t(3,    UP,         A),
    t(5,    UP,         A),
    t(7,    UP,         A),
    t(9,    UP,         A),

    t(11,   UP,         A),
    t(11.5, UP,         A),   // burst triplet
    t(12,   UP,         A),
    t(13,   UP,         A),
    t(15,   UP,         A),
    h(17,   UP,         A, 1.5),

    t(19,   UP,         A),
    t(21,   UP,         B),
    t(23,   UP,         A),
    t(25,   UP,         B),

    t(27,   UP,         A),
    t(27.5, UP,         B),   // burst triplet
    t(28,   UP,         A),
    t(29,   UP,         A),
    t(31,   UP,         A),
    t(33,   UP,         A),

    t(35,   UP_RIGHT,   A),
    t(37,   RIGHT,      A),
    t(39,   DOWN_RIGHT, A),
    t(41,   DOWN,       A),
    t(43,   DOWN_LEFT,  A),
    t(45,   LEFT,       A),
    t(47,   UP_LEFT,    A),

    t(49,   UP,         A),
    t(51,   UP,         A),
    t(53,   UP,         A),
    t(55,   UP,         A),
    t(57,   UP,         A),
    t(59,   UP,         A),
    t(61,   UP,         A),
];
